/**
 * Token build step: lib/tokens/tokens.ts -> styles/tokens.css.
 *
 * Run via `pnpm tokens` (and automatically on `prebuild`). The generated CSS
 * file is committed so the repo is usable without running the script, but it
 * is regenerated on every build to stay in lockstep with the token source.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { toCssVariables } from '../lib/tokens/tokens.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../styles/tokens.css');

const vars = toCssVariables();
const declarations = Object.entries(vars)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join('\n');

const css = `/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */
:root {
${declarations}
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css, 'utf8');

console.log(`tokens: wrote ${Object.keys(vars).length} CSS variables -> ${outPath}`);
